[Test_Flag]
enable=True

[SSID_Config]
SSID=BI1FQO-RP
Message=Testing
ICON=I

[OLED_Config]
OLED_Enable=True
OLED_Address=0x3c

[GPS_Config]
#GPS_Device="/dev/ttyAMA0"
#GPS_Option=115200

GPS_Device="10.0.6.116"
GPS_Option=12321


[SFTP_Config]
REMOTE_USER="root"
REMOTE_HOST="nas.ctsdn.com"
REMOTE_DIR="/volume1/Storage/Su7-GPS-PATH"
REMOTE_PORT="10223"
