[Test_Flag]
enable=False
#测试模式，无GPS信号时，串口和TCP模式下可以模拟定位，GPSd模式下无效

[SSID_Config]
SSID=BI1FQO-ZZ
CALLSIGN=BI1FQO
APRS_PASSWORD=20898
#密码生成：https://apps.magicbug.co.uk/passcode/index.php
ICON = I
Message=Test

[OLED_Config]
OLED_Enable=True
OLED_Address=0x3c

[SFTP_Config]
REMOTE_USER=
REMOTE_HOST=
REMOTE_DIR=
REMOTE_PORT=

[GPS_Config]
GPS_Device=GPSd
#使用GPSd服务(推荐)

#GPS_Device="/dev/ttyAMA0"
#GPS_Option=115200
#使用串口GPS模块

#GPS_Device=10.0.6.116
#GPS_Option=12321
#使用TCP GPS服务器

[PROJECT_PATH]
PROJECT_DIR=/etc/RPI_APRS